<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="2" passed="1" failed="1" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2023-12-29T09:15:55 IST" name="Default suite" finished-at="2023-12-29T09:16:07 IST" duration-ms="12141">
    <groups>
    </groups>
    <test started-at="2023-12-29T09:15:55 IST" name="Default test" finished-at="2023-12-29T09:16:07 IST" duration-ms="12141">
      <class name="TestScripts.LoginInvalid2Test">
        <test-method is-config="true" signature="setupBrowser()[pri:0, instance:TestScripts.LoginInvalid2Test@1f9f6368]" started-at="2023-12-29T09:15:55 IST" name="setupBrowser" finished-at="2023-12-29T09:16:01 IST" duration-ms="6036" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setupBrowser -->
        <test-method signature="loginbut2()[pri:1, instance:TestScripts.LoginInvalid2Test@1f9f6368]" started-at="2023-12-29T09:16:01 IST" name="loginbut2" finished-at="2023-12-29T09:16:04 IST" duration-ms="2663" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- loginbut2 -->
        <test-method signature="loginToApplicationInvalid2()[pri:2, instance:TestScripts.LoginInvalid2Test@1f9f6368]" started-at="2023-12-29T09:16:04 IST" name="loginToApplicationInvalid2" finished-at="2023-12-29T09:16:07 IST" duration-ms="3088" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Invalidcreds expected [My Account] but found [Account Login]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Invalidcreds expected [My Account] but found [Account Login]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1578)
at org.testng.Assert.assertEqualsImpl(Assert.java:150)
at org.testng.Assert.assertEquals(Assert.java:132)
at org.testng.Assert.assertEquals(Assert.java:656)
at TestScripts.LoginInvalid2Test.loginToApplicationInvalid2(LoginInvalid2Test.java:29)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:664)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:227)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:957)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:200)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:848)
at org.testng.TestRunner.run(TestRunner.java:621)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:443)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:437)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:397)
at org.testng.SuiteRunner.run(SuiteRunner.java:336)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1280)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1200)
at org.testng.TestNG.runSuites(TestNG.java:1114)
at org.testng.TestNG.run(TestNG.java:1082)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- loginToApplicationInvalid2 -->
        <test-method is-config="true" signature="closeBrowser()[pri:0, instance:TestScripts.LoginInvalid2Test@1f9f6368]" started-at="2023-12-29T09:16:07 IST" name="closeBrowser" finished-at="2023-12-29T09:16:07 IST" duration-ms="297" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- closeBrowser -->
      </class> <!-- TestScripts.LoginInvalid2Test -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
